{
 "title": "Outside",
 "description": "Outside Temperature Sensor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Today's High",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"value\") AS \"Reported\" FROM \"temperature\" WHERE \"sensor\" = '07_outside' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") AS \"Reported\" FROM \"temperature\" WHERE \"sensor\" = '07_outside' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Today's Low",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT min(\"value\") AS \"Reported\" FROM \"temperature\" WHERE \"sensor\" = '07_outside' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Estimated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") AS \"High\" FROM \"temperature\" WHERE \"sensor\" = 'estimated_outside' AND \"source\" = 'estimated_daily_max' AND $timeFilter"
    },
    {
     "query": "SELECT last(\"value\") AS \"Current\" FROM \"temperature\" WHERE \"sensor\" = 'estimated_outside' AND \"source\" = 'estimated' AND $timeFilter"
    },
    {
     "query": "SELECT last(\"value\") AS \"Low\" FROM \"temperature\" WHERE \"sensor\" = 'estimated_outside' AND \"source\" = 'estimated_daily_min' AND $timeFilter"
    }
   ]
  }
 ]
}